# Generated by Django 3.2.17 on 2023-03-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_async', '0003_alter_asynctask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='state',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('ERROR', 'Error')],
                default='PENDING',
                max_length=25,
                verbose_name='State',
            ),
        ),
    ]
