# Generated by Django 3.2.23 on 2024-01-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_async', '0004_alter_asynctask_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='traceback',
            field=models.TextField(default='', verbose_name='Traceback'),
        ),
    ]
